name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: openjdk:8-jdk

    steps:
      - uses: actions/checkout@v2

      # Set up Android SDK licenses
      - name: Accept Android SDK Licenses
        run: |
          mkdir -p $ANDROID_HOME/licenses/
          echo "24333f8a63b6825ea9c5514f83c2829b004d1fee" > $ANDROID_HOME/licenses/android-sdk-license
          echo "84831b9409646a918e30573bab4c9c91346d8abd" > $ANDROID_HOME/licenses/android-sdk-preview-license

      # Install required packages and tools
      - name: Install Android SDK
        run: |
          apt-get update
          apt-get install -y --no-install-recommends wget unzip
          wget -q https://dl.google.com/android/repository/sdk-tools-linux-4333796.zip -O android-sdk-tools.zip
          unzip -qq android-sdk-tools.zip -d $ANDROID_HOME
          yes | $ANDROID_HOME/tools/bin/sdkmanager --licenses
          yes | $ANDROID_HOME/tools/bin/sdkmanager "platforms;android-30" "build-tools;30.0.2"

      - name: Cache Buildozer global directory
        uses: actions/cache@v2
        with:
          path: .buildozer_global
          key: buildozer-global-${{ hashFiles('buildozer.spec') }}

      - uses: actions/cache@v2
        with:
          path: .buildozer
          key: ${{ runner.os }}-${{ hashFiles('buildozer.spec') }}

      - name: Build with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        id: buildozer
        with:
          command: buildozer android debug
          buildozer_version: master

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: package
          path: ${{ steps.buildozer.outputs.filename }}
