name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: cirrusci/android-sdk:30

    steps:
      - uses: actions/checkout@v2

      # Accept Android SDK Licenses
      - name: Accept Android SDK Licenses
        run: |
          mkdir -p $ANDROID_HOME/licenses/
          echo "24333f8a63b6825ea9c5514f83c2829b004d1fee" > $ANDROID_HOME/licenses/android-sdk-license
          echo "84831b9409646a918e30573bab4c9c91346d8abd" > $ANDROID_HOME/licenses/android-sdk-preview-license

      - name: Cache Buildozer global directory
        uses: actions/cache@v2
        with:
          path: .buildozer_global
          key: buildozer-global-${{ hashFiles('buildozer.spec') }}

      - uses: actions/cache@v2
        with:
          path: .buildozer
          key: ${{ runner.os }}-${{ hashFiles('buildozer.spec') }}

      - name: Build with Buildozer
        run: |
          buildozer android debug
          echo "Current directory: $(pwd)"
          echo "Listing contents:"
          ls -al

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: package
          path: ./  # This will upload everything in the current directory after the buildozer step
